# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1470f60394cf388732f4b5991fb0dee9e118cd4425d81c778d3050df78ac126ac3c8869fe7a622901f42ea62b9dbcee996c55ad4b20747bfb2ed8aaf36e5f73c

test:
  secret_key_base: c256de287f62e9d77e3bacd2ae865e768d378ffe2df5c3e5e93665df521cb84a49ea0d3aeb23f613e696daff6f89ca575d453e3342220eccc83ecd510e693fe2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
